# Generated by Django 5.1.6 on 2025-03-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_director"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieinfo",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="movieinfo",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
