# Generated by Django 5.1.6 on 2025-03-06 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_remove_movieinfo_img_movieinfo_poster"),
    ]

    operations = [
        migrations.CreateModel(
            name="censorinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.CharField(max_length=100, null=True)),
                ("certifiedby", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="movieinfo",
            name="censordetails",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movie",
                to="movies.censorinfo",
            ),
        ),
    ]
